import CCMuxCore
import Foundation

/// A session running on another Mac, resolved against this one's accounts and clock.
///
/// `startedAt` and `updatedAt` are reconstructed rather than received. The wire carries
/// ages, so they are rebuilt as `now - (age at report + how long ago the machine
/// reported)` — three clocks are involved and none of them agree, and a timestamp that
/// crossed a machine boundary would show sessions starting in the future.
public struct ForeignSession: Identifiable, Equatable, Sendable {
    /// Namespaced by machine: two Macs generate session ids independently and nothing
    /// stops them colliding, which in a SwiftUI ForEach means one row silently vanishes.
    public var id: String
    public var machineID: String
    public var machineLabel: String
    /// The *local* account id where one matches, so the session groups under the account
    /// this Mac already shows. The remote id otherwise.
    public var accountID: String
    public var accountLabel: String
    public var name: String
    public var directory: String?
    public var policy: String
    public var status: String?
    public var startedAt: Date
    public var updatedAt: Date?
    public var spendUSD: Double
    /// How long ago the reporting machine last spoke. What makes a session dim rather
    /// than lie: there is no pid to poll from here, so this is the only liveness there is.
    public var machineAge: TimeInterval

    public var isStale: Bool { machineAge > ForeignSessions.currentWithin }
}

public enum ForeignSessions {
    /// A machine reports at least every 60s, so two missed reports is the point at which
    /// something is actually wrong rather than merely quiet.
    public static let currentWithin: TimeInterval = 90
    /// Past this a sleeping laptop's sessions are worse than nothing — they read as live
    /// work that is not running.
    public static let hideAfter: TimeInterval = 15 * 60

    // MARK: - Outbound

    /// This Mac's whole list, as ages rather than timestamps.
    ///
    /// Unmanaged sessions are left out: they have no account to group under, and ccmux
    /// knows nothing about them beyond what Claude Code's own file says.
    public static func report(label: String,
                              sessions: [SessionRecord],
                              live: [Int32: ClaudeSessionInfo],
                              accountLabels: [String: String],
                              fingerprints: [String: String],
                              now: Date = Date()) -> MachineReport {
        MachineReport(label: label, sessions: sessions.map { record in
            let info = live[record.pid]
            return MachineSession(
                id: record.id,
                accountID: record.accountID,
                accountFingerprint: fingerprints[record.accountID],
                accountLabel: accountLabels[record.accountID] ?? "Unknown account",
                name: info?.name ?? Format.shortenHome(record.cwd),
                directory: record.cwd,
                policy: record.policyName,
                status: info?.status ?? "",
                startedSecondsAgo: max(0, now.timeIntervalSince(record.startedAt)),
                updatedSecondsAgo: info?.updatedAt.map { max(0, now.timeIntervalSince($0)) },
                spendUSD: record.spendUSD)
        })
    }

    // MARK: - Inbound

    /// Turns what the server holds into rows this Mac can show.
    ///
    /// `fingerprintToAccountID` maps an API key's SHA-256 to the local account holding it:
    /// such an account's id is generated by whichever Mac added it, so without this the
    /// same key looks like two different accounts.
    public static func resolve(_ machines: [MachineSnapshot],
                               excluding ownMachineID: String,
                               localAccountIDs: Set<String>,
                               fingerprintToAccountID: [String: String],
                               now: Date = Date()) -> [ForeignSession] {
        var out: [ForeignSession] = []
        for machine in machines where machine.machineID != ownMachineID {
            guard machine.ageSeconds <= hideAfter else { continue }
            let age = max(0, machine.ageSeconds)
            for session in machine.sessions {
                var accountID = session.accountID
                if !localAccountIDs.contains(accountID),
                   let fingerprint = session.accountFingerprint,
                   let local = fingerprintToAccountID[fingerprint] {
                    accountID = local
                }
                let started = now.addingTimeInterval(-(session.startedSecondsAgo + age))
                out.append(ForeignSession(
                    id: "\(machine.machineID)/\(session.id)",
                    machineID: machine.machineID,
                    machineLabel: machine.label,
                    accountID: accountID,
                    accountLabel: session.accountLabel,
                    name: session.name.isEmpty ? "claude" : session.name,
                    directory: session.directory,
                    policy: session.policy,
                    status: session.status.isEmpty ? nil : session.status,
                    startedAt: started,
                    updatedAt: session.updatedSecondsAgo
                        .map { now.addingTimeInterval(-($0 + age)) },
                    spendUSD: session.spendUSD,
                    machineAge: age))
            }
        }
        return out
    }

    /// Same order as local sessions — most wanting attention first — with the machine
    /// name breaking ties so two Macs' rows do not interleave arbitrarily.
    public static func sorted(_ sessions: [ForeignSession]) -> [ForeignSession] {
        sessions.sorted { a, b in
            let (rankA, rankB) = (SessionGrouping.Activity(status: a.status),
                                  SessionGrouping.Activity(status: b.status))
            if rankA != rankB { return rankA < rankB }
            let timeA = a.updatedAt ?? a.startedAt
            let timeB = b.updatedAt ?? b.startedAt
            if timeA != timeB { return timeA > timeB }
            if a.machineLabel != b.machineLabel { return a.machineLabel < b.machineLabel }
            return a.id < b.id
        }
    }
}
