import Foundation
import Testing
@testable import CCMuxCore
@testable import CCMuxKit

@Suite("Delegation planning")
struct DelegationTests {
    private func local(_ id: String, kind: AccountKind = .subscription,
                       label: String = "") -> Account {
        Account(id: id, label: label.isEmpty ? id : label, kind: kind)
    }

    private func remote(_ id: String, kind: AccountKind = .subscription,
                        fingerprint: String? = nil) -> RemoteAccount {
        RemoteAccount(id: id, label: id, kind: kind, apiKeyFingerprint: fingerprint)
    }

    /// A subscription's id is the Anthropic account UUID and is identical on every
    /// machine, which is the whole reason matching can be this simple.
    @Test func anAccountOnBothSidesIsDelegated() {
        let plan = Delegation.plan(local: [local("acct-1")], remote: [remote("acct-1")],
                                   delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries.count == 1)
        #expect(plan.entries.first?.disposition == .delegate)
    }

    @Test func anAccountOnlyHereIsAPushCandidate() {
        let plan = Delegation.plan(local: [local("acct-1")], remote: [],
                                   delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries(.pushCandidate).map(\.id) == ["acct-1"])
    }

    @Test func anAccountOnlyOnTheServerIsImportable() {
        let plan = Delegation.plan(local: [], remote: [remote("acct-9")],
                                   delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries(.importable).map(\.id) == ["acct-9"])
    }

    /// Reconnecting must not offer to redo work already done, or every launch would
    /// re-delegate accounts that are already delegated.
    @Test func anAlreadyDelegatedAccountIsLeftAlone() {
        let plan = Delegation.plan(local: [local("acct-1")], remote: [remote("acct-1")],
                                   delegated: ["acct-1"], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries.first?.disposition == .alreadyDelegated)
        #expect(plan.entries(.delegate).isEmpty)
    }

    /// An API-key account's id is a UUID generated by whichever Mac added it, so the two
    /// sides disagree about it. Matching on the key's fingerprint is the only thing that
    /// prevents a duplicate.
    @Test func anAPIKeyIsMatchedByFingerprintAcrossMachines() {
        let key = "sk-ant-shared"
        let plan = Delegation.plan(
            local: [local("local-uuid", kind: .apiKey, label: "Billing")],
            remote: [remote("server-uuid", kind: .apiKey, fingerprint: key.apiKeyFingerprint)],
            delegated: [],
            apiKeyFingerprint: { $0 == "local-uuid" ? key.apiKeyFingerprint : nil })

        #expect(plan.entries.count == 1)
        let entry = try! #require(plan.entries.first)
        #expect(entry.disposition == .delegate)
        // The server's id is carried so the local record can be renumbered onto it.
        #expect(entry.remoteID == "server-uuid")
    }

    @Test func aDifferentAPIKeyIsNotAMatch() {
        let plan = Delegation.plan(
            local: [local("local-uuid", kind: .apiKey)],
            remote: [remote("server-uuid", kind: .apiKey,
                            fingerprint: "sk-ant-other".apiKeyFingerprint)],
            delegated: [],
            apiKeyFingerprint: { _ in "sk-ant-mine".apiKeyFingerprint })

        #expect(plan.entries(.pushCandidate).map(\.id) == ["local-uuid"])
        #expect(plan.entries(.importable).map(\.id) == ["server-uuid"])
    }

    /// A subscription and an API key must never match each other even if the ids collide;
    /// they authenticate with different headers entirely.
    @Test func kindsAreNeverConflated() {
        let plan = Delegation.plan(local: [local("same-id", kind: .apiKey)],
                                   remote: [remote("same-id", kind: .subscription)],
                                   delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries(.pushCandidate).map(\.id) == ["same-id"])
        #expect(plan.entries(.importable).map(\.id) == ["same-id"])
    }

    @Test func aMixedEstateIsSortedIntoTheRightBuckets() {
        let plan = Delegation.plan(
            local: [local("both"), local("mine-only")],
            remote: [remote("both"), remote("theirs-only")],
            delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries(.delegate).map(\.id) == ["both"])
        #expect(plan.entries(.pushCandidate).map(\.id) == ["mine-only"])
        #expect(plan.entries(.importable).map(\.id) == ["theirs-only"])
    }
}

@Suite("Server URL")
struct ServerURLTests {
    @Test func aBareHostGetsHTTPSAndTheDefaultPort() {
        let url = Engine.normalizeServerURL("ccmux.example.com")
        #expect(url?.absoluteString == "https://ccmux.example.com:8443")
    }

    /// Both spellings have to work — the design requires reaching one server by name and
    /// by address, because a self-signed certificate carries both SANs.
    @Test func aRawIPWorksTheSameWay() {
        #expect(Engine.normalizeServerURL("203.0.113.10")?.absoluteString
                == "https://203.0.113.10:8443")
        #expect(Engine.normalizeServerURL("https://203.0.113.10:9000")?.absoluteString
                == "https://203.0.113.10:9000")
    }

    /// A trailing path would be doubled by `appendingPathComponent` and every request
    /// would 404.
    @Test func aTrailingPathIsDropped() {
        #expect(Engine.normalizeServerURL("https://host:8443/v1/")?.absoluteString
                == "https://host:8443")
        #expect(Engine.normalizeServerURL("https://host:8443/?x=1")?.absoluteString
                == "https://host:8443")
    }

    @Test func rubbishIsRejected() {
        #expect(Engine.normalizeServerURL("") == nil)
        #expect(Engine.normalizeServerURL("   ") == nil)
        #expect(Engine.normalizeServerURL("https://") == nil)
    }

    /// settings.json is plaintext on disk and is the one place the design keeps the
    /// password out of — but pasting https://user:pass@host into an address field is a
    /// natural thing to try, and the string is stored verbatim.
    @Test func embeddedCredentialsAreStripped() {
        let url = Engine.normalizeServerURL("https://ccmux:hunter2@ccmux.example.com:8443")
        #expect(url?.absoluteString == "https://ccmux.example.com:8443")
        #expect(url?.absoluteString.contains("hunter2") == false)
    }
}

@Suite("Fingerprint display")
struct FingerprintTests {
    @Test func itIsGroupedForReadingAloud() {
        let hex = String(repeating: "ab", count: 32)
        let shown = ServerFingerprint.display(hex)
        #expect(shown.hasPrefix("AB:AB:AB"))
        #expect(shown.split(separator: ":").count == 32)
    }

    @Test func theShortFormIsTruncated() {
        let short = ServerFingerprint.short(String(repeating: "cd", count: 32))
        #expect(short == "CD:CD:CD:CD:CD:CD…")
    }
}

@Suite("Grant usability")
struct GrantUsabilityTests {
    /// The credential-loss path this closes: the server returns whatever it holds even
    /// when its own refresh failed, so a grant can carry a token that expired minutes ago.
    /// Handing over on one of those overwrites the Mac's working refresh token with a dead
    /// access token, and the account is unrecoverable without a browser re-login.
    @Test func anExpiredGrantIsNotUsable() {
        let dead = TokenGrant(accountID: "a", kind: .subscription, accessToken: "stale",
                              expiresIn: 0)
        #expect(!dead.isUsable)
        #expect(!TokenGrant(accountID: "a", kind: .subscription, accessToken: "stale",
                            expiresIn: -30).isUsable)
    }

    @Test func aLiveGrantIsUsable() {
        #expect(TokenGrant(accountID: "a", kind: .subscription, accessToken: "fresh",
                           expiresIn: 3600).isUsable)
    }

    /// A server that did not state an expiry leaves the question to normal expiry
    /// handling rather than to this check.
    @Test func anUnstatedExpiryIsAccepted() {
        #expect(TokenGrant(accountID: "a", kind: .subscription, accessToken: "t").isUsable)
    }

    @Test func aGrantWithNoTokenAtAllIsNotUsable() {
        #expect(!TokenGrant(accountID: "a", kind: .subscription, expiresIn: 3600).isUsable)
        #expect(!TokenGrant(accountID: "a", kind: .subscription, accessToken: "",
                            expiresIn: 3600).isUsable)
    }

    /// An API key has no expiry — only presence matters.
    @Test func anAPIKeyGrantOnlyNeedsAKey() {
        #expect(TokenGrant(accountID: "a", kind: .apiKey, apiKey: "sk-ant-x").isUsable)
        #expect(!TokenGrant(accountID: "a", kind: .apiKey).isUsable)
        #expect(!TokenGrant(accountID: "a", kind: .apiKey, apiKey: "").isUsable)
    }
}

@Suite("Delegating to a dead server lineage")
struct ServerHealthPlanningTests {
    /// Handing an account over to a lineage the server says is dead trades a working local
    /// credential for a broken remote one.
    @Test func anAccountTheServerCannotServeIsNotDelegated() {
        let plan = Delegation.plan(
            local: [Account(id: "acct-1", label: "Mine")],
            remote: [RemoteAccount(id: "acct-1", label: "Mine", health: .needsRelogin)],
            delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries.first?.disposition == .serverNeedsRelogin)
        #expect(plan.entries(.delegate).isEmpty)
    }

    /// Nor is one worth importing sight unseen.
    @Test func aDeadServerOnlyAccountIsNotOfferedForImport() {
        let plan = Delegation.plan(
            local: [], remote: [RemoteAccount(id: "acct-9", label: "Dead",
                                              health: .needsRelogin)],
            delegated: [], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries(.importable).isEmpty)
        #expect(plan.entries(.serverNeedsRelogin).map(\.id) == ["acct-9"])
    }

    /// An account already handed over stays delegated even while the server needs signing
    /// in again — this Mac has no refresh token for it, so there is nothing to reclaim.
    @Test func anAlreadyDelegatedAccountIsNotClawedBack() {
        let plan = Delegation.plan(
            local: [Account(id: "acct-1", label: "Mine")],
            remote: [RemoteAccount(id: "acct-1", label: "Mine", health: .needsRelogin)],
            delegated: ["acct-1"], apiKeyFingerprint: { _ in nil })
        #expect(plan.entries.first?.disposition == .alreadyDelegated)
    }
}
