import Foundation
import Testing
@testable import CCMuxCore
@testable import CCMuxKit

@Suite("Sessions from other Macs")
struct ForeignSessionTests {
    private static func remote(_ id: String, account: String = "acct-1",
                               fingerprint: String? = nil,
                               label: String = "Work",
                               status: String = "busy",
                               started: TimeInterval = 600,
                               updated: TimeInterval? = 30) -> MachineSession {
        MachineSession(id: id, accountID: account, accountFingerprint: fingerprint,
                       accountLabel: label, name: id, directory: "/Users/someone/dev/\(id)",
                       policy: "opus", status: status, startedSecondsAgo: started,
                       updatedSecondsAgo: updated)
    }

    private static func machine(_ id: String, label: String, age: TimeInterval,
                                _ sessions: [MachineSession]) -> MachineSnapshot {
        MachineSnapshot(machineID: id, label: label, sessions: sessions, ageSeconds: age)
    }

    // MARK: - Resolving

    /// The whole reason ages travel instead of timestamps: two laptops and a VPS keep
    /// three clocks, so a session's real age is what it was at report time plus how long
    /// ago that report arrived.
    @Test func agesCompoundRatherThanTrustingAnyRemoteClock() {
        let now = Date(timeIntervalSince1970: 1_000_000)
        let resolved = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio", age: 40,
                          [Self.remote("api", started: 600, updated: 30)])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:],
            now: now)

        let session = try! #require(resolved.first)
        #expect(session.startedAt == now.addingTimeInterval(-640))
        #expect(session.updatedAt == now.addingTimeInterval(-70))
        #expect(session.machineAge == 40)
    }

    @Test func thisMacIsNeverAmongTheForeignOnes() {
        let resolved = ForeignSessions.resolve(
            [Self.machine("me", label: "this one", age: 1, [Self.remote("mine")]),
             Self.machine("other", label: "studio", age: 1, [Self.remote("theirs")])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:])

        #expect(resolved.map(\.name) == ["theirs"])
    }

    /// A sleeping laptop's sessions read as live work that is not running, which is worse
    /// than showing nothing at all.
    @Test func aMachineSilentTooLongDisappearsEntirely() {
        let stale = ForeignSessions.hideAfter + 1
        let resolved = ForeignSessions.resolve(
            [Self.machine("m1", label: "asleep", age: stale, [Self.remote("api")])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:])

        #expect(resolved.isEmpty)
    }

    @Test func aMachineBetweenTheThresholdsIsShownButMarkedStale() {
        let current = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio", age: 10, [Self.remote("api")])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:])
        #expect(current.first?.isStale == false)

        let quiet = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio",
                          age: ForeignSessions.currentWithin + 1, [Self.remote("api")])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:])
        #expect(quiet.count == 1)
        #expect(quiet.first?.isStale == true)
    }

    /// Two Macs generate session ids independently. Colliding ids in one SwiftUI ForEach
    /// silently drop a row, so the machine is folded into the identity.
    @Test func identicalSessionIDsOnTwoMachinesStayDistinct() {
        let resolved = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio", age: 1, [Self.remote("same")]),
             Self.machine("m2", label: "laptop", age: 1, [Self.remote("same")])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:])

        #expect(resolved.count == 2)
        #expect(Set(resolved.map(\.id)).count == 2)
    }

    /// An API-key account's id is generated by whichever Mac added it, so without the
    /// fingerprint the same key looks like two unrelated accounts and its sessions land
    /// in a group of their own.
    @Test func anAPIKeyAccountIsMatchedByFingerprintNotByID() {
        let fingerprint = "sk-ant-shared".apiKeyFingerprint
        let resolved = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio", age: 1,
                          [Self.remote("batch", account: "their-local-uuid",
                                       fingerprint: fingerprint)])],
            excluding: "me",
            localAccountIDs: ["my-local-uuid"],
            fingerprintToAccountID: [fingerprint: "my-local-uuid"])

        #expect(resolved.first?.accountID == "my-local-uuid")
    }

    @Test func anAccountThisMacDoesNotHaveKeepsItsOwnID() {
        let resolved = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio", age: 1,
                          [Self.remote("api", account: "stranger", label: "Their Work")])],
            excluding: "me", localAccountIDs: ["mine"], fingerprintToAccountID: [:])

        #expect(resolved.first?.accountID == "stranger")
        #expect(resolved.first?.accountLabel == "Their Work")
    }

    @Test func orderingMatchesLocalSessions() {
        let sessions = ForeignSessions.resolve(
            [Self.machine("m1", label: "studio", age: 1, [
                Self.remote("idle", status: "idle", updated: 5),
                Self.remote("busy", status: "busy", updated: 500),
                Self.remote("waiting", status: "waiting", updated: 900),
            ])],
            excluding: "me", localAccountIDs: ["acct-1"], fingerprintToAccountID: [:])

        // Waiting first — it is blocked on a person and will sit there until answered.
        #expect(ForeignSessions.sorted(sessions).map(\.name)
                == ["waiting", "busy", "idle"])
    }

    // MARK: - Reporting

    @Test func aReportCarriesAgesAndNoMachineLocalHandles() {
        let now = Date(timeIntervalSince1970: 2_000_000)
        let record = SessionRecord(id: "s1", pid: 42, port: 18001, accountID: "acct-1",
                                   policyName: "opus", cwd: "/Users/someone/dev/api",
                                   startedAt: now.addingTimeInterval(-300), spendUSD: 2.5)
        let info = ClaudeSessionInfo(pid: 42, sessionID: "x", cwd: "/tmp", name: "api",
                                     status: "waiting", version: nil, kind: nil,
                                     entrypoint: nil, startedAt: nil,
                                     updatedAt: now.addingTimeInterval(-12))

        let report = ForeignSessions.report(label: "studio", sessions: [record],
                                            live: [42: info],
                                            accountLabels: ["acct-1": "Work"],
                                            fingerprints: [:], now: now)

        let session = try! #require(report.sessions.first)
        #expect(session.name == "api")
        #expect(session.accountLabel == "Work")
        #expect(session.startedSecondsAgo == 300)
        #expect(session.updatedSecondsAgo == 12)
        #expect(session.status == "waiting")
        #expect(session.spendUSD == 2.5)
        // The pid and the port are machine-local; nothing on another host can act on
        // them, and their absence is what keeps a foreign card free of dead controls.
        let encoded = try! JSONStore.encoder.encode(session)
        let text = String(decoding: encoded, as: UTF8.self)
        #expect(!text.contains("18001"))
        #expect(!text.contains("\"pid\""))
    }

    @Test func aSessionClaudeCodeHasNotPublishedFallsBackToItsDirectory() {
        let record = SessionRecord(id: "s1", pid: 42, port: 18001, accountID: "acct-1",
                                   policyName: "opus", cwd: "/tmp/project")
        let report = ForeignSessions.report(label: "studio", sessions: [record], live: [:],
                                            accountLabels: [:], fingerprints: [:])

        #expect(report.sessions.first?.name == Format.shortenHome("/tmp/project"))
        #expect(report.sessions.first?.status == "")
        #expect(report.sessions.first?.accountLabel == "Unknown account")
    }

    /// A clock that steps backwards must not produce a session that started in the future.
    @Test func agesAreNeverNegative() {
        let now = Date(timeIntervalSince1970: 3_000_000)
        let record = SessionRecord(id: "s1", pid: 1, port: 9000, accountID: "a",
                                   policyName: "opus", cwd: "/tmp",
                                   startedAt: now.addingTimeInterval(600))
        let report = ForeignSessions.report(label: "studio", sessions: [record], live: [:],
                                            accountLabels: [:], fingerprints: [:], now: now)
        #expect(report.sessions.first?.startedSecondsAgo == 0)
    }
}

@Suite("Grouping with sessions from other Macs")
struct ForeignSessionGroupingTests {
    private func local(_ id: String, account: String) -> SessionRecord {
        SessionRecord(id: id, pid: 1, port: 9000, accountID: account,
                      policyName: "opus", cwd: "/tmp")
    }

    private func foreign(_ id: String, account: String, machine: String = "studio",
                         stale: Bool = false) -> ForeignSession {
        ForeignSession(id: "\(machine)/\(id)", machineID: machine, machineLabel: machine,
                       accountID: account, accountLabel: "Their Work", name: id,
                       directory: nil, policy: "opus", status: "busy",
                       startedAt: Date(), updatedAt: nil, spendUSD: 0,
                       machineAge: stale ? ForeignSessions.currentWithin + 10 : 5)
    }

    @Test("Foreign sessions join their account's group without joining its count")
    func foreignSitsUnderItsAccount() {
        let groups = SessionGrouping.groups(
            accounts: [PolicyEngineTests.account("a")],
            sessions: [local("s1", account: "a")],
            unmanaged: [],
            foreign: [foreign("f1", account: "a"), foreign("f2", account: "a")])

        #expect(groups.map(\.id) == ["a"])
        // `count` means "running here" everywhere it is already used.
        #expect(groups[0].count == 1)
        #expect(groups[0].foreignCount == 2)
        #expect(groups[0].sessions.map(\.id) == ["s1"])
        #expect(groups[0].isForeignOnly == false)
    }

    @Test("An account with nothing running here still gets a group for what runs elsewhere")
    func foreignOnlyGroupForAKnownAccount() {
        let groups = SessionGrouping.groups(
            accounts: [PolicyEngineTests.account("a")],
            sessions: [],
            unmanaged: [],
            foreign: [foreign("f1", account: "a")])

        #expect(groups.map(\.id) == ["a"])
        #expect(groups[0].count == 0)
        #expect(groups[0].isForeignOnly)
    }

    /// The reason `accountLabel` travels on the wire: without it this group would be
    /// titled with eight characters of someone else's UUID.
    @Test("An account only another Mac has is titled from what that Mac called it")
    func anUnknownAccountIsNamedByItsReporter() {
        let groups = SessionGrouping.groups(
            accounts: [PolicyEngineTests.account("a")],
            sessions: [local("s1", account: "a")],
            unmanaged: [],
            foreign: [foreign("f1", account: "stranger")])

        #expect(groups.map(\.id) == ["a", "stranger"])
        #expect(groups[1].title == "Their Work")
        #expect(groups[1].subtitle == "not on this Mac")
        #expect(groups[1].isForeignOnly)
    }

    @Test("Foreign sessions for a removed account join its orphan group")
    func orphanGroupsTakeTheirForeignSessions() {
        let groups = SessionGrouping.groups(
            accounts: [PolicyEngineTests.account("a")],
            sessions: [local("s1", account: "a"), local("s2", account: "deleted")],
            unmanaged: [],
            foreign: [foreign("f1", account: "deleted")])

        #expect(groups.map(\.id) == ["a", "deleted"])
        #expect(groups[1].title == "Unknown account")
        #expect(groups[1].foreignCount == 1)
        // Exactly one group per account, whichever side the sessions came from.
        #expect(Set(groups.map(\.id)).count == groups.count)
    }

    @Test("The unmanaged group stays last, after any foreign-only group")
    func unmanagedRemainsLast() {
        let info = ClaudeSessionInfo(pid: 7, sessionID: "x", cwd: "/tmp", name: nil,
                                     status: nil, version: nil, kind: nil,
                                     entrypoint: nil, startedAt: nil)
        let groups = SessionGrouping.groups(
            accounts: [PolicyEngineTests.account("a")],
            sessions: [local("s1", account: "a")],
            unmanaged: [info],
            foreign: [foreign("f1", account: "stranger")])

        #expect(groups.map(\.id) == ["a", "stranger", SessionGrouping.unmanagedGroupID])
    }

    /// The toggle is off, so `foreign` arrives empty and the screen is exactly what it
    /// was before the feature existed.
    @Test("With nothing foreign passed in, grouping is unchanged")
    func noForeignSessionsIsTheOldBehaviour() {
        let groups = SessionGrouping.groups(
            accounts: [PolicyEngineTests.account("a")],
            sessions: [local("s1", account: "a")],
            unmanaged: [])

        #expect(groups.map(\.id) == ["a"])
        #expect(groups[0].foreign.isEmpty)
        #expect(groups[0].isForeignOnly == false)
    }
}

@Suite("Hostile numbers off the wire")
struct WireNumberTests {
    /// `Int(Double)` traps — on NaN and on anything past Int.max — and these ages arrive
    /// as bare float64 from another machine, then land in a SwiftUI view body, where a
    /// fatal error takes the window with it. Verified before the clamp: exit 133, SIGTRAP.
    @Test func durationSurvivesAnythingAMachineCouldReport() {
        // Read from an array so the compiler cannot fold these into the call site.
        let hostile: [TimeInterval] = [.nan, .infinity, -.infinity, 1e300, -1e300,
                                       .greatestFiniteMagnitude,
                                       TimeInterval(Int.max), -1]
        for value in hostile {
            #expect(!Format.duration(value).isEmpty)
        }
    }

    @Test func ordinaryDurationsStillReadTheWayTheyShould() {
        #expect(Format.duration(0) == "0s")
        #expect(Format.duration(45) == "45s")
        #expect(Format.duration(90) == "1m")
        #expect(Format.duration(3600) == "1h")
        #expect(Format.duration(5400) == "1h 30m")
        #expect(Format.duration(-5) == "0s")
    }
}

@Suite("The API key fingerprint cache")
struct APIKeyFingerprintCacheTests {
    /// The bug this type exists to prevent: keying the check off what was successfully
    /// read means an unreadable Keychain item never gets accounted for, so every tick
    /// rebuilds the whole cache — N blocking `security` calls, every 20 seconds, forever.
    @Test func anUnreadableKeyDoesNotForceARebuildEveryTime() {
        var reads = 0
        let reader: (String) -> String? = { accountID in
            reads += 1
            return accountID == "readable" ? "sk-ant-value" : nil
        }
        var cache = APIKeyFingerprintCache()
        let accounts: Set<String> = ["readable", "locked"]

        let built = cache.refresh(accountIDs: accounts, reading: reader)
        #expect(built)
        #expect(reads == 2)
        #expect(cache["readable"] == "sk-ant-value".apiKeyFingerprint)
        #expect(cache["locked"] == nil)

        // The account set has not moved, so nothing is re-read.
        let again = cache.refresh(accountIDs: accounts, reading: reader)
        let third = cache.refresh(accountIDs: accounts, reading: reader)
        #expect(again == false)
        #expect(third == false)
        #expect(reads == 2)
    }

    @Test func anAccountAppearingOrLeavingRebuilds() {
        var cache = APIKeyFingerprintCache()
        let first = cache.refresh(accountIDs: ["a"]) { _ in "key-a" }
        let grown = cache.refresh(accountIDs: ["a", "b"]) { id in "key-\(id)" }
        #expect(first)
        #expect(grown)
        #expect(cache["b"] == "key-b".apiKeyFingerprint)

        let shrunk = cache.refresh(accountIDs: ["a"]) { _ in "key-a" }
        #expect(shrunk)
        #expect(cache["b"] == nil)
    }

    /// A key rewritten under an id that did not change is invisible to the account set,
    /// and a stale fingerprint silently stops matching that account across machines.
    @Test func invalidatingForcesARereadUnderAnUnchangedAccountSet() {
        var key = "first"
        var cache = APIKeyFingerprintCache()
        let built = cache.refresh(accountIDs: ["a"]) { _ in key }
        #expect(built)

        key = "second"
        let unchanged = cache.refresh(accountIDs: ["a"]) { _ in key }
        #expect(unchanged == false)
        #expect(cache["a"] == "first".apiKeyFingerprint)

        cache.invalidate()
        let rebuilt = cache.refresh(accountIDs: ["a"]) { _ in key }
        #expect(rebuilt)
        #expect(cache["a"] == "second".apiKeyFingerprint)
    }

    /// Invalidating has to drop the answers, not just the scope. With the scope cleared
    /// and no API-key accounts left, the next refresh compares two empty sets, returns
    /// early, and a fingerprint belonging to a deleted account would live on — matching
    /// foreign sessions onto an account that no longer exists.
    @Test func invalidatingClearsTheAnswersAndNotOnlyTheScope() {
        var cache = APIKeyFingerprintCache()
        cache.refresh(accountIDs: ["gone"]) { _ in "sk-ant-old" }
        #expect(cache["gone"] != nil)

        cache.invalidate()
        let rebuilt = cache.refresh(accountIDs: []) { _ in nil }
        #expect(rebuilt == false)
        #expect(cache["gone"] == nil)
        #expect(cache.byFingerprint.isEmpty)
    }

    @Test func theInverseMapIsWhatMatchesAForeignSession() {
        var cache = APIKeyFingerprintCache()
        cache.refresh(accountIDs: ["local-uuid"]) { _ in "sk-ant-shared" }
        let inverse = cache.byFingerprint
        #expect(inverse["sk-ant-shared".apiKeyFingerprint] == "local-uuid")
    }
}

@Suite("A server too old for session sharing")
struct OlderServerTests {
    /// The upgrade order nobody controls: a Mac updates before the VPS does, and every
    /// one of these routes answers 404. Reported as "the server is old", never as a
    /// failure — otherwise the window fills with errors every 20 seconds.
    ///
    /// That the old server really does answer 404 is the Go side's to prove; this is the
    /// half that decides what the answer means.
    @Test func aMissingRouteIsRecognisedRatherThanReportedAsAFailure() {
        #expect(ServerClient.isMissingRoute(ServerClientError.http(404, "not found")))
        #expect(ServerClient.isMissingRoute(ServerClientError.http(405, "")))

        // Everything else is a real failure and must keep its own message.
        #expect(!ServerClient.isMissingRoute(ServerClientError.http(500, "boom")))
        #expect(!ServerClient.isMissingRoute(ServerClientError.unauthorized))
        #expect(!ServerClient.isMissingRoute(ServerClientError.transport("no route to host")))
        #expect(!ServerClient.isMissingRoute(ServerClientError.incompatible(2)))
    }

    @Test func theUnsupportedMessagePointsAtTheServer() {
        let message = ServerClientError.unsupported.localizedDescription
        #expect(message.lowercased().contains("server"))
    }
}

@Suite("This Mac's identity on the server")
struct MachineIdentityTests {
    @Test func aBlankLabelFallsBackRatherThanBecomingEmpty() {
        #expect(!MachineIdentityStore.defaultLabel().isEmpty)
        let identity = MachineIdentity(id: "keep-me", label: "studio")
        #expect(MachineIdentityStore.renamed(identity, to: "   ").label
                == MachineIdentityStore.defaultLabel())
    }

    /// Renaming must never change *which machine this is*. Reading the identity back from
    /// disk to rename it would mint a fresh id whenever the support directory is
    /// unwritable — `JSONStore.save` returns nothing and swallows the failure — leaving a
    /// ghost machine on the server for every rename and every launch after it.
    @Test func renamingKeepsTheIdentity() {
        let identity = MachineIdentity(id: "8f0f1b64-0000-4000-8000-000000000001",
                                       label: "studio")
        let renamed = MachineIdentityStore.renamed(identity, to: "  laptop  ")
        #expect(renamed.id == identity.id)
        #expect(renamed.label == "laptop")
    }

    /// The identity lives in its own file precisely so that settings — the thing people
    /// copy between Macs — cannot carry a machine id along with them.
    @Test func theIdentityIsNotPartOfSettings() throws {
        // Settings is what gets copied between Macs, and two of them reporting under one
        // id would overwrite each other's session list on every tick. `Settings` having
        // no `MachineIdentity`-shaped member is the thing being pinned — checking the
        // encoded text for "machineID" proves nothing, since the identity encodes its
        // fields as `id` and `label`.
        let mirror = Mirror(reflecting: Settings())
        #expect(!mirror.children.contains { $0.value is MachineIdentity })
        #expect(Paths.machineFile.lastPathComponent == "machine.json")
        #expect(Paths.machineFile != Paths.settingsFile)
    }

    @Test func showingForeignSessionsDefaultsOnAndSurvivesAnOlderSettingsFile() throws {
        #expect(Settings().showForeignSessions)
        // A settings.json written before the key existed must not fail the whole decode
        // and silently reset every other choice to its default.
        let older = Data(#"{"warnThresholdPercent": 9, "autoSwitch": "off"}"#.utf8)
        let decoded = try JSONStore.decoder.decode(Settings.self, from: older)
        #expect(decoded.warnThresholdPercent == 9)
        #expect(decoded.autoSwitch == .off)
        #expect(decoded.showForeignSessions)
    }
}
